name: Haskell CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GHC
        uses: haskell-actions/setup@v2.7.5
        with:
          ghc-version  : 9.8.2
          cabal-version: 3.12.1.0
          enable-stack: false

      - name: Install dependencies
        run: cabal update

      - name: Build project
        run: cabal build

      - name: Run tests
        run: cabal test